// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAypRP86PPq3jWOoWiWY7BaFC6gkItPuvk',
    appId: '1:1009671565006:web:7171b688664478ba0e6a9f',
    messagingSenderId: '1009671565006',
    projectId: 'zyraflow-production',
    authDomain: 'zyraflow-production.firebaseapp.com',
    storageBucket: 'zyraflow-production.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9eMu4PA8fKggxW0Ne2kYVV0WQr5EKXIs',
    appId: '1:1009671565006:android:67dcc937b380eff90e6a9f',
    messagingSenderId: '1009671565006',
    projectId: 'zyraflow-production',
    storageBucket: 'zyraflow-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Hq3GY82L3LxBcynFfIo8js6G6FGtg3Q',
    appId: '1:1009671565006:ios:8dbd46fa23d21e3c0e6a9f',
    messagingSenderId: '1009671565006',
    projectId: 'zyraflow-production',
    storageBucket: 'zyraflow-production.firebasestorage.app',
    iosBundleId: 'com.zyraflow.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Hq3GY82L3LxBcynFfIo8js6G6FGtg3Q',
    appId: '1:1009671565006:ios:5a9a268d9ec73b940e6a9f',
    messagingSenderId: '1009671565006',
    projectId: 'zyraflow-production',
    storageBucket: 'zyraflow-production.firebasestorage.app',
    iosBundleId: 'com.zyraflow.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAypRP86PPq3jWOoWiWY7BaFC6gkItPuvk',
    appId: '1:1009671565006:web:28599e0ffd9e17340e6a9f',
    messagingSenderId: '1009671565006',
    projectId: 'zyraflow-production',
    authDomain: 'zyraflow-production.firebaseapp.com',
    storageBucket: 'zyraflow-production.firebasestorage.app',
  );

}